### ISSUE TITLE
Add pagination for the book display

### ISSUE THREAD

**Issue by athenacats** [athenacats/soma#2]
On the home page, and all the book pages, 90 books are loaded. Pagination should be implemented where the number of books shown is 30.

Optionally, a dropdown menu can be placed so that the user can choose how many books should be displayed per page.

Please leave a comment before commencing. Feel free to ask for clarification as well.

**Comment by rohit-chaware** [comment]
Hey @athenacats I would like to work on this issue.

**Comment by athenacats** [comment]
Hey! You can go ahead. If you have any questions, feel free to reach out

**Comment by rohit-chaware** [comment]
I am getting error while running the server.

![image](https://github.com/athenacats/soma/assets/80148306/abfbeaca-6b8d-43ef-8bed-6ed560919b15)

**Comment by athenacats** [comment]
I think it's because you don't have access to the .env file. Let me share it in a few hours once I'm next to my comp.

**Comment by athenacats** [comment]
Hey! So sorry for the delay. I have sent you an invite to a private repo in which you can find the .env file. Copy that file into the backend -> src folder. 

Alternatively, check for changes in the original parent repository where I have created a `.env.example` file, whose location shows where the .env file should be created, and the content inside has the same instructions as above. As always, if you need any clarifications, reach out below :)

**Comment by rohit-chaware** [comment]
Still I am getting the same error. 
I copied the .env file from the private repo you send in the `backend->src` folder.
After that I run the `npm start` command, but still getting the error as above.

**Comment by athenacats** [comment]
I apologize for that. Let me find out what the issue is then I'll ping you once it's fixed so that you can resume. I'll close the issue for now then reassign it to you once the MOngoDB issue is fixed

**Comment by athenacats** [comment]
I apologize for that. Let me find out what the issue is then I'll ping you once it's fixed so that you can resume. I'll close the issue for now then reassign it to you once the MongoDB issue is fixed

**Comment by rohit-chaware** [comment]
Ya sure. Take your time ✌
